### ISSUE TITLE
Azimuth and distance plugin for QGIS 2.X does not work

### ISSUE THREAD

**Issue by giedrioks26** [mpetroff/qgsazimuth#1]
Fill out your coordinates and I click on the "Draw", Writes error:

An error has occured while executing Python code: 

Traceback (most recent call last): 
  File "/home/giedrius/.qgis2/python/plugins/qgsAzimuth/qgsAzimuth.py", line 188, in addgeometry 
    if (surveytype== 'polygonal'): 
UnboundLocalError: local variable 'surveytype' referenced before assignment 

Python version: 
2.7.3 (default, Jan  2 2013, 14:09:21) 
[GCC 4.7.2] 

QGIS version: 
2.1.0-Master Master, exported 

Python path: ['/home/giedrius/.qgis2/python/plugins/processing', '/usr/share/qgis/python', u'/home/giedrius/.qgis2/python', u'/home/giedrius/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', '/usr/share/qgis/python', '/home/giedrius/.qgis2/python/plugins/mmqgis/forms', '/usr/share/qgis/python/plugins/fTools/tools', '/home/giedrius/.qgis2/python/plugins/DigitizingTools/tools', '~/.qgis/python', '/media/sda4/home/giedrius/Dokumentai/qgis']

**Comment by mpetroff** [comment]
I think this was fixed in v0.9.2.
