### ISSUE TITLE
Azimuth format problem in QGIS Desktop 2.14.3

### ISSUE THREAD

**Issue by jbrowne11** [mpetroff/qgsazimuth#11]
System: Windows 10, QGIS Desktop 2.14.3, Azimuth and Distance Plugin version 0.9.6, CRS EPSG: 102746

Azimuths in dd.mm.ss format run as expected. Azimuths in N/S xD x' x" E/W format do not; all results appear to be in the NE quadrant. Several tests run, including the following: 
angle=Azimuth
heading=Coordinate_System
dist_units=Default
startAt=11834366.1648;6993182.3863;90
survey=Polygonal
[data]
N 0D E;500.0;90
N 90D E;500.0;90
S 0D E;500.0;90
S 90D W;500.0;90

**Comment by mpetroff** [comment]
You're using [bearings, not azimuths](https://engineering.purdue.edu/~asm215/topics/bearings.html), but have the angle type set to "azimuth." Change the angle type to "bearing" in the options tab to use bearings.

**Comment by jbrowne11** [comment]
Thank you for correcting my misunderstanding. And for maintaining this important plugin.
