### ISSUE TITLE
Distance Problem

### ISSUE THREAD

**Issue by knightscove** [mpetroff/qgsazimuth#12]
When I enter in a distance it creates a line 100's of miles long.

For example, if I enter in a course 127 feet long it draws a line from Maryland USA to the the middle of the Atlantic Ocean?

If I edit the entry in the list and change the distance to .000127 it creates a line a few hundred feet long.

Any guidance is appreciated.
Thanks

**Comment by mpetroff** [comment]
What CRS are you using? The plugin only works with planar coordinate systems such as NAD83, not angular ones such as WGS84.

**Comment by knightscove** [comment]
I am using WGS84. Thanks for letting me know what I had wrong for the plugin

Tm
