### ISSUE TITLE
Strange results when making a curve

### ISSUE THREAD

**Issue by TheDude005** [mpetroff/qgsazimuth#13]
I was inserting segments for a parcel of land when the last segment was to be a curve.  When I entered in the required information the curve became two segments shaped like a sideways v veering off from the rest of the segments.  I tried it with many different numbers and different information entered and still the same thing it would make two segments joined at an angle but never a curve (which I understand would be made up of many segments along the curve rather than a true curve).  The information for the curve is:
Delta 018d 34' 33"
Radius 970.00'
Tangent 158.63'
Length 314.48'
Chord Bearing S 1d 33' 03" E
Chord 313.11'

I entered this information with the chord bearing in the azimuth box, the radius in the radius box, and the length in the distance box.  The zenith was left at the default 90 and the offset was 0.  I have included a screenshot.  I don't know if I am putting inputs into incorrect boxes or if something else is going on.  I have included a screenshot of my options as well.
![azimutherror](https://user-images.githubusercontent.com/4662595/29245934-8121cc32-7faf-11e7-9f0c-bf1d0853e8c0.png)
![azimuthoptions](https://user-images.githubusercontent.com/4662595/29245935-8121fa86-7faf-11e7-832a-623301bcd018.png)

**Comment by mpetroff** [comment]
This was a regression introduced in v0.9.8. I fixed it ab2e62611a33cb46f5686090eb32f46415b161dc and released v0.9.9 (you should be able to update from within QGIS once the new release I uploaded is approved in the plugins repository).
