### ISSUE TITLE
Segment List Import & Export

### ISSUE THREAD

**Issue by ksandell7** [mpetroff/qgsazimuth#14]
Just noticed that you fixed drawing arcs, which makes this plugin very usable for our purposes.  With that said, the import & export segment list appears to leave out the data for Radius & Direction.  I was able to quickly modify the export process by adding the following at lines 919 and 920 of qgsAzimuth.py   --    +str(self.pluginGui.table_segmentList.item(row, 3).text()) +';' \
+str(self.pluginGui.table_segmentList.item(row, 4).text()) 

so that when the calls contain a curve the radius and direction information is stored in the export.

However, when I import, it ignores the 2 additional columns of data.  Without studying the code a bit more I am not seeing how to alter the import to include that additional information.   Would it be possible to get this included?

**Comment by mpetroff** [comment]
I just added import and export support for arcs in 8970c427f6948f0134de80326a3aef7c928bbd97 and uploaded v0.9.10 to the plugins repository.
