### ISSUE TITLE
Error creating arc segments with Anti-clockwise selected

### ISSUE THREAD

**Issue by spatialconnections** [mpetroff/qgsazimuth#16]
Arc is incorrectly drawn when entering a new anti-clockwise curve.  All clockwise curves seem to work correctly.  I have tried this on my MacBook Pro with Mac OS X 10.12, Windows 10, and Windows 7 computers with QGIS 2.18.13 and 2.18.15.  I have attached two files, one is a image to show the error, and the second is the exported segment list used to re-create this.  CRS used was EPSG:3436 and EPSG:102672.  Options settings are Survey type: Boundary, Angle type: Bearing, Distance unit: Feet, Angle unit: Degree, North type: Default(0.0 and Azimuth 1 & 2 are 0), Drawing: Arc lines: 6, Open attribute form is checked.

<img width="1021" alt="qgis_azimuth_anticlockwise_error" src="https://user-images.githubusercontent.com/3478066/35082275-81975f1e-fbde-11e7-8ae1-7c837ce4a3f3.png">

[QGIS_Azimuth_Anticlockwise_Segment_Export.txt](https://github.com/mpetroff/qgsazimuth/files/1641692/QGIS_Azimuth_Anticlockwise_Segment_Export.txt)

**Comment by mpetroff** [comment]
This should be fixed now. I just uploaded v0.9.11 with the fix to the plugin repository; it is currently awaiting approval.
