### ISSUE TITLE
Plugin approval- add metadata

### ISSUE THREAD

**Issue by NyakudyaA** [mpetroff/qgsazimuth#17]
Add homepage to metadata.txt
![metadata](https://user-images.githubusercontent.com/2510900/35210101-840d1c06-ff59-11e7-8ead-3f73faac3bc9.png)

**Comment by mpetroff** [comment]
There is no homepage, just this code repository and issue tracker, which are both listed. I don't see any reason to add the same URL twice (code repository URL as homepage URL).
