### ISSUE TITLE
QGIS resultant shape correct by way too big!

### ISSUE THREAD

**Issue by dougbrugg** [mpetroff/qgsazimuth#26]
Thanks in advance for reading and any advice!  I set my layer projections to NAD83 [4269] to draw surveyor results across a parcel in the US. Define the starting point using decimal degrees. Under Options I selected "Bearing" and under Distance unit "Default" was selected. I loaded the csv file with azimuth and distance using ; as separator. Distance units are ft. Clicking draw produces the right shape but at a huge magnitude. The projection of the resulting shape is NAD 83 [4269]. Any ideas would be great!!

**Comment by mpetroff** [comment]
This plugin uses Euclidean geometry, so it only works with planar projections, not ellipsoidal coordinate systems such as NAD83 or WGS84. See https://github.com/mpetroff/qgsazimuth/issues/12#issuecomment-291692157.

**Comment by mpetroff** [comment]
While it doesn't work with NAD83 directly, it works fine with the NAD83 state plane zones.

**Comment by dougbrugg** [comment]
Got it - really appreciate it!!

**Comment by mpetroff** [comment]
A check to warn the user if an unsupported geographic CRS is used was added in https://github.com/mpetroff/qgsazimuth/commit/c68bd3933040fbe888f13d5f29fe2f7cbb8b1997 / v0.9.19.
