### ISSUE TITLE
How to calculate the Azimuth 

### ISSUE THREAD

**Issue by QGISHelp** [mpetroff/qgsazimuth#27]
Hey! I am trying to calculate the azimuth, I want to calculate the degree of one point based off another and I have about 200 data points total to calculate for. Any suggestions for plugins to use? Azimuth and Distance plugin is not working.

**Comment by mpetroff** [comment]
> Azimuth and Distance plugin is not working.

Care to elaborate?

This plugin is for going from azimuths and distances to coordinates, not the other way around. If what you think isn't working is the fact that the plugin doesn't allow you to go from a set of points to azimuths and distances, it isn't a bug, it's just out-of-scope for the plugin. If what isn't working is something, please elaborate.

**Comment by QGISHelp** [comment]
Oh ok I guess I am using the wrong tool to achieve my goal then. Basically I have multiple points that are different distances away from a main point. I need to calculate the degree of each of those points based off the main point. Is there another way to do this?

**Comment by mpetroff** [comment]
Yes, this is the wrong tool.

I quick search turned up some StackExchange posts that might be helpful:
https://gis.stackexchange.com/questions/245524/measuring-distance-between-points-using-qgis
https://gis.stackexchange.com/questions/155810/how-to-calculate-azimuth-in-qgis-field-calculator

However, it's not something I've ever tried to do.
