### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by rjhale1971** [mpetroff/qgsazimuth#4]
I've been working with the Azimuth and Bearings Plugin - Some Suggestions/Problems/Requests: 

Enhancement: Can we specify a layer to add data to - right now it defaults to a tmp file 
Enhancement: Capture from map -> Can we specify a feature. Example - I have a GPS point in QGS. Would it be possible to snap to it? I can hand type it but it introduces error. 
Possible Problem: If I specify Distance Units in Feet it appears to be dividing by Feet. Line is much shorter than it shoudl be. Leaving it at default seems to be correct

**Comment by NathanW2** [comment]
@rjhale1971 these should be fixed now after DMS did some improvements to this plugin.
