### ISSUE TITLE
Can't add feature

### ISSUE THREAD

**Issue by teaguejust** [mpetroff/qgsazimuth#9]
I am working with a polygon layer.  Once I hit 'draw' I am faced with an error dialog and the feature is not being added to the layer (whether custom or in memory).  My interpretation is that the error is occurring when the attribute form is supposed to be shown.

The error is below:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/jteague/.qgis2/python/plugins\qgsAzimuth\qgsAzimuth.py", line 261, in addgeometry
    form.setIsAddDialog(True)
AttributeError: 'QDialog' object has no attribute 'setIsAddDialog'

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.2.0-Valmiera Valmiera, c3a2817

Python path: ['C:/Users/jteague/.qgis2/python/plugins\\processing', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\requests-2.0.1-py2.7.egg', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\raven-3.5.1-py2.7.egg', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\nose_html-1.1-py2.7.egg', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\gsconfig-0.6.9-py2.7.egg', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\gsimporter-0.1-py2.7.egg', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\python_dateutil-2.2-py2.7.egg', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\six-1.7.3-py2.7.egg', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\lxml-3.3.5-py2.7-win32.egg', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\opengeo\\ext-libs\\httplib2-0.9-py2.7.egg', 'C:/PROGRA~1/QGISVA~1/apps/qgis/./python', u'C:/Users/jteague/.qgis2/python', u'C:/Users/jteague/.qgis2/python/plugins', 'C:/PROGRA~1/QGISVA~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISVA~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISVA~1\\bin', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISVA~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\mmqgis/forms', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\opengeo\\ext-libs', '~/.qgis/python', '.', 'C:\\PROGRA~1\\QGISVA~1\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\Users\\jteague\\.qgis2\\python\\plugins\\geopunt4Qgis\\ext-libs']

**Comment by mpetroff** [comment]
Update your version of QGIS. While I neglected to update the metadata, at least version 2.4 is required (fixed in 7d696594e024cb97b1c877fd2291cbd914d7cb14).
